import WidgetKit
import SwiftUI

// MARK: - Shared data

// Must match APP_GROUP / KEY in mobile/lib/widget.ts.
private let appGroup = "group.app.tvtime.personal"
private let storageKey = "upNext"

struct UpNextItem: Codable, Identifiable {
    let id: Int
    let show: String
    let code: String
    let detail: String
}

struct UpNextData: Codable {
    let updatedAt: String
    let count: Int
    let items: [UpNextItem]
}

func loadUpNext() -> UpNextData? {
    guard
        let defaults = UserDefaults(suiteName: appGroup),
        let json = defaults.string(forKey: storageKey),
        let data = json.data(using: .utf8),
        let decoded = try? JSONDecoder().decode(UpNextData.self, from: data)
    else {
        return nil
    }
    return decoded
}

// Sample used for the widget gallery / placeholder before the app has run.
let sampleData = UpNextData(
    updatedAt: "",
    count: 5,
    items: [
        UpNextItem(id: 1, show: "Severance", code: "S02E05", detail: "Aired 2 days ago"),
        UpNextItem(id: 2, show: "The Bear", code: "S03E01", detail: "Aired today"),
        UpNextItem(id: 3, show: "Shrinking", code: "S02E08", detail: "Aired 5 days ago"),
    ]
)

// MARK: - Timeline

struct UpNextEntry: TimelineEntry {
    let date: Date
    let data: UpNextData
}

struct Provider: TimelineProvider {
    func placeholder(in context: Context) -> UpNextEntry {
        UpNextEntry(date: Date(), data: sampleData)
    }

    func getSnapshot(in context: Context, completion: @escaping (UpNextEntry) -> Void) {
        let data = context.isPreview ? sampleData : (loadUpNext() ?? sampleData)
        completion(UpNextEntry(date: Date(), data: data))
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<UpNextEntry>) -> Void) {
        let entry = UpNextEntry(date: Date(), data: loadUpNext() ?? sampleData)
        // The app reloads the timeline whenever the backlog changes; refresh a
        // few hours out anyway so relative dates ("2 days ago") stay honest.
        let next = Calendar.current.date(byAdding: .hour, value: 6, to: Date())!
        completion(Timeline(entries: [entry], policy: .after(next)))
    }
}

// MARK: - Views

// Asset names generated by the target's color config (expo-target.config.js).
private let accent = Color("$accent")
private let bg = Color("$widgetBackground")

struct Header: View {
    let count: Int
    var body: some View {
        HStack(spacing: 5) {
            Image(systemName: "play.tv.fill")
                .font(.system(size: 11, weight: .bold))
                .foregroundColor(accent)
            Text("UP NEXT")
                .font(.system(size: 11, weight: .heavy, design: .rounded))
                .tracking(1.2)
                .foregroundColor(accent)
            Spacer(minLength: 0)
            if count > 0 {
                Text("\(count)")
                    .font(.system(size: 11, weight: .bold, design: .rounded))
                    .foregroundColor(.white.opacity(0.55))
            }
        }
    }
}

struct EmptyView: View {
    var body: some View {
        VStack(spacing: 6) {
            Image(systemName: "checkmark.circle.fill")
                .font(.system(size: 26))
                .foregroundColor(accent)
            Text("All caught up")
                .font(.system(size: 13, weight: .semibold, design: .rounded))
                .foregroundColor(.white)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}

struct SmallWidget: View {
    let data: UpNextData
    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            Header(count: data.count)
            Spacer(minLength: 6)
            if let item = data.items.first {
                Text(item.show)
                    .font(.system(size: 17, weight: .bold, design: .rounded))
                    .foregroundColor(.white)
                    .lineLimit(2)
                Text(item.code)
                    .font(.system(size: 12, weight: .heavy, design: .rounded))
                    .foregroundColor(accent)
                    .padding(.top, 2)
                Text(item.detail)
                    .font(.system(size: 11, weight: .medium, design: .rounded))
                    .foregroundColor(.white.opacity(0.5))
                    .padding(.top, 1)
            } else {
                EmptyView()
            }
            Spacer(minLength: 0)
        }
    }
}

struct Row: View {
    let item: UpNextItem
    var body: some View {
        HStack(spacing: 8) {
            VStack(alignment: .leading, spacing: 1) {
                Text(item.show)
                    .font(.system(size: 13, weight: .semibold, design: .rounded))
                    .foregroundColor(.white)
                    .lineLimit(1)
                Text(item.detail)
                    .font(.system(size: 10, weight: .medium, design: .rounded))
                    .foregroundColor(.white.opacity(0.45))
                    .lineLimit(1)
            }
            Spacer(minLength: 4)
            Text(item.code)
                .font(.system(size: 11, weight: .heavy, design: .rounded))
                .foregroundColor(accent)
        }
    }
}

struct MediumWidget: View {
    let data: UpNextData
    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            Header(count: data.count)
            if data.items.isEmpty {
                EmptyView()
            } else {
                ForEach(Array(data.items.prefix(3))) { item in
                    Row(item: item)
                }
                Spacer(minLength: 0)
            }
        }
    }
}

struct UpNextWidgetEntryView: View {
    @Environment(\.widgetFamily) var family
    var entry: Provider.Entry

    var body: some View {
        Group {
            switch family {
            case .systemMedium:
                MediumWidget(data: entry.data)
            default:
                SmallWidget(data: entry.data)
            }
        }
        .widgetBackground(bg)
    }
}

struct UpNextWidget: Widget {
    let kind = "UpNextWidget"

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: Provider()) { entry in
            UpNextWidgetEntryView(entry: entry)
        }
        .configurationDisplayName("Up Next")
        .description("The next episodes waiting in your TV Time backlog.")
        .supportedFamilies([.systemSmall, .systemMedium])
    }
}

// containerBackground is required on iOS 17+ widgets; fall back for iOS 16.
extension View {
    @ViewBuilder
    func widgetBackground(_ color: Color) -> some View {
        if #available(iOS 17.0, *) {
            containerBackground(color, for: .widget)
        } else {
            padding(14).background(color)
        }
    }
}

struct UpNextWidget_Previews: PreviewProvider {
    static var previews: some View {
        UpNextWidgetEntryView(entry: UpNextEntry(date: Date(), data: sampleData))
            .previewContext(WidgetPreviewContext(family: .systemSmall))
    }
}
